import React from 'react';
import Head from 'next/head';
import { useState } from 'react';
import { useRouter } from 'next/router';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import AdminLayout from '@/components/layouts/AdminLayout';
import { teachersService } from '@/services/teachers.service';
import { teacherSchema, TeacherSchema } from '@/utils/validation';
import {
    User,
    Briefcase,
    Plus,
    ArrowLeft,
    ShieldCheck,
    AlertCircle,
    Mail,
    Phone,
    Calendar,
    MapPin,
    GraduationCap,
    Save,
    Clock
} from 'lucide-react';

const tabs = [
    { id: 'personal', label: 'Identity Matrix', icon: User },
    { id: 'professional', label: 'Professional Protocol', icon: Briefcase },
];

export default function AddTeacher() {
    const router = useRouter();
    const [activeTab, setActiveTab] = useState('personal');
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [status, setStatus] = useState<{ type: 'success' | 'error', message: string } | null>(null);

    const {
        register,
        handleSubmit,
        formState: { errors },
        reset,
    } = useForm<TeacherSchema>({
        resolver: zodResolver(teacherSchema),
        defaultValues: {
            gender: 'OTHER' as any,
        }
    });

    const onSubmit = async (data: TeacherSchema) => {
        setIsSubmitting(true);
        setStatus(null);
        try {
            // Note: employeeId is usually generated by backend, but we include it if needed by DTO
            // For now, mapping as per service.create expectations
            await teachersService.create({
                ...data,
                employeeId: `TCH-${Math.random().toString(36).substr(2, 6).toUpperCase()}`, // Simulated ID if not provided
                dateOfJoining: data.joiningDate,
            } as any);

            setStatus({ type: 'success', message: 'New faculty entity successfully initialized and registered in the directory.' });
            setTimeout(() => router.push('/admin/teachers'), 2000);
        } catch (err: any) {
            setStatus({ type: 'error', message: err.message || 'Entity registration sequence failed. Protocol aborted.' });
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
      <>
        
            <Head>
                <title>Onboard Faculty - EduCore</title>
            </Head>

            {/* Header Section */}
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
                <div className="flex flex-col gap-1">
                    <button
                        onClick={() => router.back()}
                        className="flex items-center gap-2 text-slate-400 hover:text-primary transition-colors mb-4 group"
                    >
                        <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
                        <span className="text-[10px] font-black uppercase tracking-widest">Protocol Directory</span>
                    </button>
                    <h1 className="text-4xl font-black text-slate-900 dark:text-white tracking-tight">Onboard Faculty</h1>
                    <p className="text-slate-500 dark:text-slate-400 font-medium italic">Initialize a new faculty entity record within the institutional ecosystem.</p>
                </div>
                <div className="flex gap-4">
                    <button
                        form="add-teacher-form"
                        type="submit"
                        disabled={isSubmitting}
                        className="px-8 py-4 bg-primary text-white rounded-2xl font-black text-sm shadow-xl shadow-primary/20 hover:-translate-y-1 active:scale-95 transition-all flex items-center gap-2 disabled:opacity-50"
                    >
                        {isSubmitting ? <Clock className="animate-spin" size={18} /> : <Plus size={18} />}
                        Initialize Entity
                    </button>
                </div>
            </div>

            {status && (
                <div className={`p-6 rounded-[2rem] border flex items-center gap-4 mb-10 animate-in fade-in slide-in-from-top-4 ${status.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-500' : 'bg-rose-500/10 border-rose-500/20 text-rose-500'
                    }`}>
                    {status.type === 'success' ? <ShieldCheck size={24} /> : <AlertCircle size={24} />}
                    <p className="text-sm font-bold tracking-tight">{status.message}</p>
                </div>
            )}

            {/* Main Interface */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
                {/* Navigation Sidebar */}
                <div className="lg:col-span-3 space-y-2">
                    {tabs.map((tab) => {
                        const Icon = tab.icon;
                        const isActive = activeTab === tab.id;
                        return (
                            <button
                                key={tab.id}
                                onClick={() => setActiveTab(tab.id)}
                                className={`w-full flex items-center gap-4 px-6 py-5 rounded-[1.5rem] transition-all relative overflow-hidden group ${isActive
                                        ? 'bg-primary text-white shadow-xl shadow-primary/20 translate-x-2'
                                        : 'bg-white dark:bg-slate-900 text-slate-500 border border-slate-200 dark:border-slate-800 hover:border-primary/30'
                                    }`}
                            >
                                <Icon size={20} className={isActive ? 'animate-pulse' : 'group-hover:text-primary transition-colors'} />
                                <span className="text-[10px] font-black uppercase tracking-widest leading-none">{tab.label}</span>
                                {isActive && <div className="absolute right-0 top-0 h-full w-1.5 bg-white/20" />}
                            </button>
                        );
                    })}
                </div>

                {/* Form Area */}
                <div className="lg:col-span-9">
                    <form id="add-teacher-form" onSubmit={handleSubmit(onSubmit)} className="space-y-10">
                        {activeTab === 'personal' && (
                            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-10 lg:p-12 shadow-sm space-y-10 animate-in fade-in slide-in-from-right-4">
                                <div className="flex items-center gap-4 mb-4">
                                    <div className="p-3 rounded-2xl bg-primary/10 text-primary">
                                        <User size={24} />
                                    </div>
                                    <div>
                                        <h3 className="text-xl font-black text-slate-900 dark:text-white tracking-tight">Identity Matrix</h3>
                                        <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1">Core Registry Parameters</p>
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                    <FormField label="First Identifier" icon={User} error={errors.firstName?.message}>
                                        <input {...register('firstName')} className="form-input" placeholder="e.g. Sarah" />
                                    </FormField>
                                    <FormField label="Last Identifier" icon={User} error={errors.lastName?.message}>
                                        <input {...register('lastName')} className="form-input" placeholder="e.g. Connor" />
                                    </FormField>
                                    <FormField label="Digital Endpoint" icon={Mail} error={errors.email?.message}>
                                        <input {...register('email')} className="form-input" placeholder="sarah.c@educore.edu" />
                                    </FormField>
                                    <FormField label="Signal Frequency" icon={Phone} error={errors.phone?.message}>
                                        <input {...register('phone')} className="form-input" placeholder="+1 (555) 000-0000" />
                                    </FormField>
                                    <FormField label="Gender Axis" icon={ShieldCheck}>
                                        <select {...register('gender')} className="form-input">
                                            <option value="MALE">Male Vector</option>
                                            <option value="FEMALE">Female Vector</option>
                                            <option value="OTHER">Alternative Axis</option>
                                        </select>
                                    </FormField>
                                    <FormField label="Deployment Coordinates" icon={MapPin} className="md:col-span-2">
                                        <textarea {...register('address')} rows={3} className="form-input py-4 resize-none" placeholder="Primary residence address..." />
                                    </FormField>
                                </div>

                                <div className="flex justify-end pt-4">
                                    <button
                                        type="button"
                                        onClick={() => setActiveTab('professional')}
                                        className="flex items-center gap-2 px-6 py-3 bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-white rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-primary hover:text-white transition-all group"
                                    >
                                        Next Protocol
                                        <ArrowLeft size={14} className="rotate-180 group-hover:translate-x-1 transition-transform" />
                                    </button>
                                </div>
                            </div>
                        )}

                        {activeTab === 'professional' && (
                            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-10 lg:p-12 shadow-sm space-y-10 animate-in fade-in slide-in-from-right-4">
                                <div className="flex items-center gap-4 mb-4">
                                    <div className="p-3 rounded-2xl bg-indigo-500/10 text-indigo-500">
                                        <Briefcase size={24} />
                                    </div>
                                    <div>
                                        <h3 className="text-xl font-black text-slate-900 dark:text-white tracking-tight">Professional Protocol</h3>
                                        <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mt-1">Institutional Status Matrix</p>
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                                    <FormField label="Departmental Matrix" icon={Briefcase} error={errors.department?.message}>
                                        <select {...register('department')} className="form-input">
                                            <option value="">Select Sector</option>
                                            <option value="Mathematics">Mathematics</option>
                                            <option value="Science">Science</option>
                                            <option value="Languages">Languages</option>
                                            <option value="Arts">Humanities & Arts</option>
                                        </select>
                                    </FormField>
                                    <FormField label="Initial Designation" icon={ShieldCheck} error={errors.designation?.message}>
                                        <input {...register('designation')} className="form-input" placeholder="e.g. Junior Faculty" />
                                    </FormField>
                                    <FormField label="Onboarding Date" icon={Calendar} error={errors.joiningDate?.message}>
                                        <input {...register('joiningDate')} type="date" className="form-input" />
                                    </FormField>
                                    <FormField label="Academic Credentials" icon={GraduationCap} error={errors.qualification?.message} className="md:col-span-2">
                                        <input {...register('qualification')} className="form-input" placeholder="e.g. M.Ed, B.Sc" />
                                    </FormField>
                                </div>

                                <div className="flex justify-between pt-4">
                                    <button
                                        type="button"
                                        onClick={() => setActiveTab('personal')}
                                        className="flex items-center gap-2 px-6 py-3 bg-slate-100 dark:bg-slate-800 text-slate-900 dark:text-white rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-slate-200 dark:hover:bg-slate-700 transition-all group"
                                    >
                                        <ArrowLeft size={14} className="group-hover:-translate-x-1 transition-transform" />
                                        Identity Matrix
                                    </button>
                                    <button
                                        type="submit"
                                        disabled={isSubmitting}
                                        className="flex items-center gap-2 px-10 py-4 bg-primary text-white rounded-2xl font-black text-xs uppercase tracking-widest shadow-xl shadow-primary/20 hover:-translate-y-1 active:scale-95 transition-all disabled:opacity-50"
                                    >
                                        {isSubmitting ? <Clock className="animate-spin" size={16} /> : <Save size={16} />}
                                        Finalize Deployment
                                    </button>
                                </div>
                            </div>
                        )}
                    </form>
                </div>
            </div>

            <style jsx>{`
        .form-input {
          @apply w-full px-5 py-4 bg-slate-50 dark:bg-slate-800/50 border-none rounded-2xl text-sm font-bold text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-primary/20 transition-all placeholder:text-slate-400 placeholder:italic placeholder:font-normal;
        }
      `}</style>
        
      </>
    );
}

function FormField({ label, icon: Icon, children, error, className = "" }: any) {
    return (
        <div className={`flex flex-col gap-2 ${className}`}>
            <div className="flex items-center gap-2 ml-2">
                <Icon size={14} className="text-slate-400" />
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{label}</label>
            </div>
            {children}
            {error && (
                <p className="text-[10px] font-bold text-rose-500 italic ml-2 mt-1 flex items-center gap-1 animate-in slide-in-from-left-2">
                    <AlertCircle size={10} />
                    {error}
                </p>
            )}
        </div>
    );
}


AddTeacher.getLayout = function getLayout(page: React.ReactElement) {
  return <AdminLayout>{page}</AdminLayout>;
};
